version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: bash aws ecr get-login --no-include-email --region eu-west-1 > dockerlogin.sh \
                  chmod 777 dockerlogin.sh \
                  ./dockerlogin.sh \
                  rm dockerlogin.sh 

      #- run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      #- run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      #- run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG && sleep 10

      #- store_artifacts:
      #    path: Dockerfile
